name = "OctofitterRadialVelocity"
uuid = "c6a353d9-c9c1-48aa-9c23-64f4679bd07d"
authors = ["William Thompson <will.thompson@outlook.com>"]
version = "7.0.1"

[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
AstroImages = "fe3fc30c-9b16-11e9-1c73-17dabf39f4ad"
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Octofitter = "daf3887e-d01a-44a1-9d7e-98f15c5d69c9"
PlanetOrbits = "fd6f9641-d78f-43ce-a379-ceb0bddb468a"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
OctofitterRadialVelocityMakieExt = ["Makie"]

[compat]
AbstractGPs = "0.5"
AstroImages = "0.5"
Bumper = "0.7.0"
CSV = "0.10"
DataDeps = "0.7"
Distances = "0.10"
Distributions = "0.25"
FITSIO = "0.16, 0.17"
MCMCChains = "6.0"
Octofitter = "7"
PlanetOrbits = "0.11"
Polynomials = "4.0.19"
Random = "1"
StaticArrays = "1.6"
StatsBase = "0.33, 0.34"
StringDistances = "0.11"
Tables = "1.10"
TypedTables = "1.4"
julia = "1.9"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CairoMakie", "Random"]
